version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env.dev
    depends_on:
      - db
    networks:
      - quickchat-network

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: quickchat
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev@123
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - quickchat-network

volumes:
  db-data:

networks:
  quickchat-network:
