version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/quickchat
      - SPRING_DATASOURCE_USERNAME=dev
      - SPRING_DATASOURCE_PASSWORD=dev@123
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: quickchat
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev@123
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
